[package]
name = "testsignal"
version = "0.2.0"
authors = ["Tatu Peltola"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte = "0.2"
clap = "2.33.3"
